### ISSUE TITLE
A problem during Preprocessing

### ISSUE THREAD

**Issue by CiE-XinYuChen** [ming024/FastSpeech2#106]
NOW,I have a problem during preprocessing.
When i running about

> python3 preprocess.py config/LJSpeech/preprocess.yaml

before that,I already unzip MFA into `preprocessed_data/LJSpeech/TextGrid/.`

While i run it ,It looks like Processing Data but it did't work and :

_Processing Data ...
  0%|                                                                                                                                             | 0/1 [00:00<?, ?it/s]_
And i don't know what cause this problem.Anyone can help me?
T
Thanks!

**Comment by CiE-XinYuChen** [comment]
Maybe my config was wrong.Who have an idea?

**Comment by jerryuhoo** [comment]
This is because tqdm shows the progress bar of different speakers. If you only have one speaker, then it will show 1/1. It took long time to process, for me it's 2 hours, so just wait.
Or you can change line 67-69 in preprocessor.py (Haven't test yet, maybe it should work)
```
for i, speaker in enumerate(os.listdir(self.in_dir)):
    speakers[speaker] = i
        for wav_name in tqdm(os.listdir(os.path.join(self.in_dir, speaker))):
```

**Comment by CiE-XinYuChen** [comment]
Thanks verymuch! @jerryuhoo i already found the problem because SSH timeout.Thanks for your advice!

**Comment by HY-2837** [comment]
> This is because tqdm shows the progress bar of different speakers. If you only have one speaker, then it will show 1/1. It took long time to process, for me it's 2 hours, so just wait.这是因为 tqdm 显示不同说话人的进度条。如果您只有一个扬声器，则它将显示 1/1。处理时间很长，对我来说是 2 小时，所以请等待。 Or you can change line 67-69 in preprocessor.py (Haven't test yet, maybe it should work)或者您可以在 preprocessor.py 中更改第 67-69 行（还没有测试，也许它应该可以）
> 
> ```
> for i, speaker in enumerate(os.listdir(self.in_dir)):
>     speakers[speaker] = i
>         for wav_name in tqdm(os.listdir(os.path.join(self.in_dir, speaker))):
> ```

It did work!
