### ISSUE TITLE
Mismatch Tensor Size issue

### ISSUE THREAD

**Issue by azman-i** [ming024/FastSpeech2#108]
if you face mismatch tensor size error then this issue is for you.

- 1)First make batch size=1
- 2)Then print batch in train.py after `for batch in batches line`
- 3)Then run your code.
- 4)See the last file that the code took as a batch
- 5)Open the textgrid file of that corresponding file and try to find out which phoneme is missing.
- 6)It might be a punctuation which was introduced by MFA(in my case it was a dot).And include it into symbol list in symbols.py with a @.For . i added "@.".
- 7)Run the code again and repeat the loop

**Comment by sayalijadhao19** [comment]
@azman-i  did you get the solution for this problem?
