### ISSUE TITLE
Noisy and irrelevant voice generated

### ISSUE THREAD

**Issue by azman-i** [ming024/FastSpeech2#109]
Almost trained 100000 steps with 18 hours of data.But the sound generated till now is still not clear and not even slightly audible.What could be the possible reason?

**Comment by jerryuhoo** [comment]
Hi, I met the same problem that the output was irrelevant. I trained my own dataset with the mandarin MFA model, I didn't use the dictionary that this repo provided. I use the dictionary from https://github.com/Jackiexiao/MTTS/blob/master/misc/mandarin-for-montreal-forced-aligner-pre-trained-model.lexicon. 
How was your training lost? After 20000 steps, my lost dropped to about 1.8.
```
Validation Step 20000, Total Loss: 1.8106, Mel Loss: 0.5992, Mel PostNet Loss: 0.5991, Pitch Loss: 0.1508, Energy Loss: 0.3317, Duration Loss: 0.1298
```
And I use multi-speaker dataset. Each speaker has around 120 wav files. The total number of speakers is around 800. Is it possible that I have too many speakers and the number of sound samples from each speaker is too small?

**Comment by jerryuhoo** [comment]
OK, I solved my problem. It was the issue of the symbols.py. I changed this file according to #66 zhangbo2008's fix. But I found the sequence that a symbol maps to the index was random. Therefore, every time when I inferenced, the outputs were always not the same.

**Comment by azman-i** [comment]
Hi,I also solved my problem.I didn't change vocoder for my language which is universal vocoder.Afte changing it synthesis was alright.

**Comment by zaynabmu** [comment]
> Hi,I also solved my problem.I didn't change vocoder for my language which is universal vocoder.Afte changing it synthesis was alright.

Could you please tell me where the change made in which file? and the lexion.txt use your language or the same in the original code? thank you
