### ISSUE TITLE
Can I finetune one people's voice (my own voice) with this model ?And how ?

### ISSUE THREAD

**Issue by Tian14267** [ming024/FastSpeech2#120]
Hi, can you tell me how to finetune one people's voice ,so I can get a specific people's speech？can you tell me the steps ? And how much( or how long ) the duration of this one-people's funetune data should be ?

**Comment by TaridaGeorge** [comment]
Why closing this?

**Comment by aidosRepoint** [comment]
> Why closing this?

I'm also wondering. The question is very interesting.
