### ISSUE TITLE
Inference error size:mismatch

### ISSUE THREAD

**Issue by yanzhuangzhuang-beep** [ming024/FastSpeech2#127]
when i  use the config "python synthesize.py --text "大家好，欢迎收听我的频道" --speaker_id 0 --restore_step 100000 --m
ode single -p config/AISHELL3/preprocess.yaml -m config/AISHELL3/model.yaml -t config/AISHELL3/train.yaml"
Then show a problem

 size mismatch for speaker_emb.weight: copying a param with shape torch.Size([218, 256]) from checkpoint, the shape in current model is torc
h.Size([1, 256]).

**Comment by zaynabmu** [comment]
@yanzhuangzhuang-beep Hi how did you solve this problem ? I faced it currently

thank you in advance
