### ISSUE TITLE
Mismatch tensor when training custom data

### ISSUE THREAD

**Issue by lethanhson9901** [ming024/FastSpeech2#129]
Thanks for your excellent work!
I trained new custom data in Vietnamese, I don't know clearly how this repo work. I followed to your pipeline with my own lexicon file and there is no error until I ran train.py
 
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main(args, configs)
  File "train.py", line 82, in main
    output = model(*(batch[2:]))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/FastSpeech2/model/fastspeech2.py", line 91, in forward
    d_control,
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/FastSpeech2/model/modules.py", line 121, in forward
    x = x + pitch_embedding
RuntimeError: The size of tensor a (64) must match the size of tensor b (104) at non-singleton dimension 1
Training:   0% 1/900000 [00:00<148:47:19,  1.68it/s]
Epoch 1:   0% 0/166 [00:00<?, ?it/s]

I also checked module.py but had no idea to fix this. 

This is some example in my lexicon file:
![image](https://user-images.githubusercontent.com/49090718/143978403-f221e9f5-697b-4be8-b7eb-650cc2465874.png)

I also changed symbol.py file:
![image](https://user-images.githubusercontent.com/49090718/143978694-abed9541-8ae2-4b99-8825-c021b7f7d02a.png)

Here is example of output TextGrid file:
![image](https://user-images.githubusercontent.com/49090718/143978880-c5f3549a-f783-494f-bd48-a1817b08d9ac.png)

Please help me!

**Comment by yanzhuangzhuang-beep** [comment]
I have the save problem with you
what shold i change  about symbol.py

**Comment by yanzhuangzhuang-beep** [comment]
![30ac6e183ab0ec4a8cf9e792009cd2e](https://user-images.githubusercontent.com/62825785/144042310-24f581c1-bdb6-4d68-a6bd-81498e4a5e40.png)
I think that text_to_sequence function  like the picture cause the problem 
some text like 'er' can not be index  so pitch(51)>text(49)

**Comment by chenming6615** [comment]
Have a try of this solution :

https://github.com/ming024/FastSpeech2/issues/131#issuecomment-993298268

**Comment by lethanhson9901** [comment]
problem solved. Many thanks !

**Comment by samin9796** [comment]
@Lethanhson9901 How did you solve the problem?
