### ISSUE TITLE
AISHELL3 alignment textgrid does not actually match audio well 

### ISSUE THREAD

**Issue by wwdok** [ming024/FastSpeech2#138]
I downloaded the AISHELL3 alignment textgrids from your google deive sharing, then open one of the textgrid and its audio using praat software, i  found the words and phones segements do not match its audio content well:
![image](https://user-images.githubusercontent.com/43233772/148680433-457e46ef-4997-4403-b0a3-9d81338c977a.png)
Is these textgrids really okay for training?
By the way, the prertained aishell3 model you provided synthesizes audio not bad, do you train model on these textgrids ?
Thanks in advance !

**Comment by Tian14267** [comment]
It can't make an exact match. Even you train it your self .But it doesn't affect training as long as it has no very serious and quite a lot of error.

**Comment by tobechao** [comment]
@wwdok Hi, I have the same problem as you, the phoneme and the duration time are not matched, sometimes misaligned, have you solved it?  Which mfa version are you use?

**Comment by wwdok** [comment]
@tobechao Afterwards, i found other textgrids matched better, maybe i happened to meet the textgrid that bad matched. Also, i found teh textgrid provided by paddlespeech seems not bad: https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3/tts3

**Comment by tobechao** [comment]
> @tobechao Afterwards, i found other textgrids matched better, maybe i happened to meet the textgrid that bad matched. Also, i found teh textgrid provided by paddlespeech seems not bad: https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3/tts3

en, But much less textgrids and speakers, only 174 speakers; I've tried several mfa versions: 1.0.1, 1.1.0.beta2, 2.0.0.rc3 and it doesn't work, sometimes very serious misaligned, do you have a solution?
