### ISSUE TITLE
solution about RuntimeError: isDifferentiableType(variable.scalar_type()) 

### ISSUE THREAD

**Issue by Mao-JianGuo** [ming024/FastSpeech2#14]
In modules.py    change 
`  self.pitch_bins = nn.Parameter(torch.exp(torch.linspace(np.log(hp.f0_min), np.log(hp.f0_max), hp.n_bins-1)))
   self.energy_bins = nn.Parameter(torch.linspace(hp.energy_min, hp.energy_max, hp.n_bins-1))`

to
`  self.pitch_bins = torch.exp(torch.linspace(np.log(hp.f0_min), np.log(hp.f0_max), hp.n_bins-1)).cuda()
        self.energy_bins = torch.linspace(hp.energy_min, hp.energy_max, hp.n_bins-1).cuda()`

_Originally posted by @Mao-JianGuo in https://github.com/ming024/FastSpeech2/issues/13#issuecomment-673223123_

**Comment by ming024** [comment]
Thank you all, closed #14
