### ISSUE TITLE
Speed control?

### ISSUE THREAD

**Issue by mailong25** [ming024/FastSpeech2#15]
Thanks for amazing work.
Is this implementation allows speed control (adjust speaking rate become faster or slower) ?
If not, where should I look for to implement this feature?

**Comment by ming024** [comment]
@mailong25 I did not implement it in this work for simplicity, but I think it is quiet easy. Just change this line https://github.com/ming024/FastSpeech2/blob/35efa49ecf79cfbcec058248a42a5eedcbf967d2/modules.py#L87 to
```
out.append(vec.expand(int(expand_size * speed_ratio), -1)) 
```
You can set the variable `speed_ratio` to be 1 by default, and set it to any desired value at inference time. I think you don't event need to retrain the model.

**Comment by ming024** [comment]
closed #15

**Comment by ming024** [comment]
closed #15

**Comment by ayush-1506** [comment]
@ming024 Quick question: What's the best way to control other variance parameters (pitch, energy)?

**Comment by johannahom** [comment]
@ayush-1506 have you figured this out yet? I was also interested. Cannot seem to see an obvious way from the code.

**Comment by Pydataman** [comment]
mark
the result of speed_control is bad 
exp speed_control=0.9
