### ISSUE TITLE
assert batch_size * group_size < len(dataset)

### ISSUE THREAD

**Issue by zaynabmu** [ming024/FastSpeech2#156]
hello everyone,

I tried to train the model in my dataset and this error comes out could you please help me this is Traceback (most recent call last):
File "/content/drive/MyDrive/FastSpeech2/train.py", line 198, in
main(args, configs)
File "/content/drive/MyDrive/FastSpeech2/train.py", line 32, in main
assert batch_size * group_size < len(dataset)
AssertionError

thank you

**Comment by WoBuChiTang** [comment]
Hi,have you  fix this error?

**Comment by WoBuChiTang** [comment]
@zaynabmu 
Hi, have you  fixed this error?

**Comment by zaynabmu** [comment]
You have to increase the size of the dataset at least more than 2 hours

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
