### ISSUE TITLE
Error while training Russian model

### ISSUE THREAD

**Issue by Nistrian** [ming024/FastSpeech2#18]
Hi, thanks for the job! I have a problem. I am trying to teach the Russian language to the model. The only thing I changed in your code is the kind of cleaner by specifying transliteration_cleaner, since Cyrillic can be transliterated. I went through the TextGrids creation step as well as the preprocess.py step. Run train.py. An error occurs:
![image](https://user-images.githubusercontent.com/69087388/96610065-e3a4f380-1303-11eb-91cc-978a918e1497.png)
how can i solve this problem?

**Comment by juliakorovsky** [comment]
@Nistrian Ideally, you should have some system that will transliterate your dataset and then you can specify symbols you used for that in 'valid symbols' in file cmu_dict.
