### ISSUE TITLE
Question of Training Time

### ISSUE THREAD

**Issue by leijue222** [ming024/FastSpeech2#19]
In README, here is:

> The model takes less than 10k steps (less than 1 hour on my GTX1080 GPU) of training to generate audio samples with acceptable quality

I clone this project, use the same dataset and parameters on GTX1080Ti (Two GPUs).  The log is:
![2020-10-24 20-50-01屏幕截图](https://user-images.githubusercontent.com/30276789/97082204-904fdf80-163a-11eb-9f55-68d6332a7b31.png)

It seems to need 4.2 days to complete. Is somewhere I made a mistake?

**Comment by leijue222** [comment]
The code I changed the following two places:
1. https://github.com/ming024/FastSpeech2/issues/13#issuecomment-698263168
2. https://github.com/ming024/FastSpeech2/issues/14#issuecomment-678245971
Otherwise, I cannot run train.py.

**Comment by leijue222** [comment]
![屏幕截图 2020-10-26 10:58:12](https://user-images.githubusercontent.com/30276789/97129737-9d73e800-177a-11eb-97f4-a120a07e35a2.png)

Yes, you're right. The model takes less than 10k steps will have a pretty result. 
After that, the improvement is tiny, especially after 50K (about three and a half hours). Sometimes the effect of individual words is worse.

**Comment by hhm853610070** [comment]
I am very sorry to bother you.How about the quality of the audio you synthesized in the test phase.I use the model with Chinese dataset.When I set the pitch and energy normalization = False and use the frame level feature of them，the loss is much higher compared to you(pitch:~1500 energy:~150 in train and pitch ~8000 ~400 in validation).The audio quality is poor. There are many noises and incorrect pronunciations in the synthesized audio when i use the test data,but both the train and val audio  synthesized in trainning step is good.
