### ISSUE TITLE
How can one control the F0 at synthesis time?

### ISSUE THREAD

**Issue by johannahom** [ming024/FastSpeech2#21]
Hi there,

I am wondering since the paper for FastSpeech 2 is about being able to control factors such as F0, how this can be done synthesis time. I would like to add a scaling factor for F0 or duration, but cannot seem to do it in synthesis.py.

Thanks!

**Comment by ming024** [comment]
@johannahom Inference-time control is supported now!

**Comment by johannahom** [comment]
Thanks so much! Great repo, looking forward to adding some more controllable features :)
