### ISSUE TITLE
求救！！在VarianceAdaptor中 进行pith_embeding的时候显示编码器输出张量x和音素嵌入张量形状不同无法相加

### ISSUE THREAD

**Issue by aaqq112** [ming024/FastSpeech2#216]
![image](https://github.com/ming024/FastSpeech2/assets/143687569/9e87141e-5cab-4da8-94c7-9b894078d586)
![image](https://github.com/ming024/FastSpeech2/assets/143687569/bab9cb65-5052-47f4-8270-30fad993ad2f)
我是一个深度学习小白 请问各位 这两个张量的各个维度代表什么为什么会出现大小不一致的现象呢 求救！！各位大佬

**Comment by Qianqian1220** [comment]
解决了吗，家人，我也有这个问题
