### ISSUE TITLE
textgrid

### ISSUE THREAD

**Issue by ada-k** [ming024/FastSpeech2#24]
We are implementing the model using a different dataset, are we supposed to produce new text grids or is there a way we can customize ljspeechtextgrids? 
If we're to produce new text grids, which method is the most appropriate to use for all the wav files?

**Comment by asarsembayev** [comment]
@ada-k 
Hi! You should produce TextGrids for each new dataset. MFA can be used for this purpose.
You can either train an acoustic model from [scratch](https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/train_acoustic_model.html) or [align](https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/workflows/alignment.html) the textgrids with a pretrained model.
