### ISSUE TITLE
Implementation of Pitch predictor

### ISSUE THREAD

**Issue by harsh-99** [ming024/FastSpeech2#25]
Hi,

Thanks for your contribution. As mentioned in the paper for pitch they predict Pitch spectogram, mean and variance however it's not implemented in the current repo. Could you kindly tell if I am wrong or if that part is needed to be implemented.
Regards
Harsh

**Comment by ming024** [comment]
@harsh-99 Hello. I think the pitch spectrogram is added in the 2nd version of FastSpeech 2 (after the deadline of NeuRIPS but before it is submitted to ICLR) and this repo refers to the 1st version of FastSpeech 2 (and I think the audio quality is OK). Maybe you can try to implement it and tell me the difference :)

**Comment by ming024** [comment]
closed #25
