### ISSUE TITLE
Share OS version problem with MFA

### ISSUE THREAD

**Issue by AppleHolic** [ming024/FastSpeech2#28]
- previous OS : Ubuntu 16.04
- solve OS : Ubuntu 18.04

I faced a problem that a compiled binary has a version dependency and its version depend on versions of Ubuntu (upper than 18.04). 

Probably, I guess from log files that latest shared library of MFA is compiled on ubuntu 18.04 or upper.

So, I upgraded to ubuntu 18.04, then mfa successfully can be run. 

(* but be careful while doing it! )

Freely close this issue after you see it.

**Comment by ming024** [comment]
Thanks for your share! It will be useful for other users!
