### ISSUE TITLE
No speakers.json

### ISSUE THREAD

**Issue by zhangsanfeng86** [ming024/FastSpeech2#29]
Hello,
Thank you for ur update

Could you share ur speaker.json

**Comment by ming024** [comment]
OK, it's updated in the newest commit.

**Comment by zhangsanfeng86** [comment]
Thank you for ur quick reply!!!
And could you give a discript as follow: (in ./config/AISHELL3/preprocess.yaml)
I want to retrain the model,  could you tell the function of the four path?

path:
  corpus_path: "/home/ming/Data/AISHELL-3"
  lexicon_path: "lexicon/pinyin-lexicon-r.txt"
  raw_path: "./raw_data/AISHELL3"
  preprocessed_path: "./preprocessed_data/AISHELL3"

Thank you!
