### ISSUE TITLE
align AISHELL3 the corpus ERR

### ISSUE THREAD

**Issue by zhangsanfeng86** [ming024/FastSpeech2#30]
Hello,

When Ialign the AISHELL3 corpus by myself,  got error . As Follow:
![image](https://user-images.githubusercontent.com/73547638/109767586-ba419000-7c32-11eb-81ed-33b487b56744.png)

Maybe the document lexicon.txt is wrong?

**Comment by ming024** [comment]
@zhangsanfeng86 Did you use a pretrained model or train the MFA from scratch?
