### ISSUE TITLE
AdaIN-VC speaker encoder support

### ISSUE THREAD

**Issue by HudsonHuang** [ming024/FastSpeech2#31]
Hi, thank you for your work, it's awesome.

I participated in your lecture about M2VoC. You shared the approach of using AdaIN-VC as speaker encoder, it was impressive. 
But the code here seems to only support lookup tables, any plan for it?
https://github.com/ming024/FastSpeech2/blob/76b2b657262b645898ec9db0a1eb6ff2319cfee6/model/fastspeech2.py#L38

**Comment by ming024** [comment]
@HudsonHuang please refer to the "M2VoC" branch for the code used in the M2VoC challenge. However, I did not put the code of AdaIN-VC in this repository. You can check [AdaIN-VC](https://github.com/cyhuang-tw/AdaIN-VC)

**Comment by ming024** [comment]
Closed #31
