### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for FastSpeech2:

### ISSUE THREAD

**Issue by leminhnguyen** [ming024/FastSpeech2#32]
- When I tried to load the pretrained model `output/LJSpeech/ckpt/900000.pth.tar`, I have some errors: 
```
size mismatch for encoder.src_word_emb.weight: copying a param with shape torch.Size([361, 256]) from checkpoint, the shape in current model is torch.Size([151, 256]).
```

- The code which loads the model from repo
```python
base_config_path = "config/LJSpeech"
prepr_path = f"{base_config_path}/preprocess.yaml"
model_path = f"{base_config_path}/model.yaml"
train_path = f"{base_config_path}/train.yaml"

prepr_config = yaml.load(open(prepr_path, "r"), Loader=yaml.FullLoader)
model_config = yaml.load(open(model_path, "r"), Loader=yaml.FullLoader)
train_config = yaml.load(open(train_path, "r"), Loader=yaml.FullLoader)
configs = (prepr_config, model_config, train_config)
cpkt_path = "output/LJSpeech/ckpt/900000.pth.tar"

def get_model(ckpt_path, configs):
    (preprocess_config, model_config, train_config) = configs
    model = FastSpeech2(preprocess_config, model_config).to(device)
    ckpt = torch.load(ckpt_path)
    model.load_state_dict(ckpt["model"])
    model.eval()
    model.requires_grad_ = False
    return model
```

**Comment by ming024** [comment]
@leminhnguyen I guess the pretrained model includes the pinyin phones, but they are not included in your model for some reason?

**Comment by leminhnguyen** [comment]
@ming024  Thanks you, got it. I figured out my problem, I commented out the `_pinyin` line incidentially.
- Additional question: How does Fastspeech2 recognize the end of syllable ?

**Comment by ming024** [comment]
@leminhnguyen I am not sure what you mean but I assume that you are asking that how the model knows that there should be a short pause between each Chinese character. We didn't give the model any extra information but the phoneme sequence, so I think that the model can learn this automatically by recognizing the vowels in the phoneme sequence.

**Comment by leminhnguyen** [comment]
@ming024  Thanks for your time. You're right. 
In addition to, I think the quality of audio can be improved more if you finetune the generated mel-spectrogram with **HifiGan**. I've tried to finetune with **Tacotron** and **HifiGan** and got the better results. To finetune with **HifiGan** the size of generated melspectrogram must equal the size of the ground truth. This can be done by using `Teacher Forcing` mode in **Tacotron**, but with the **FastSpeech** I don't have any idea to do that, so did you have any suggestion ? If I can finetune **Hifigan** with **FastSpeech**, I'll report the result.

Thanks in advance

**Comment by ming024** [comment]
@leminhnguyen It is a good suggestion. I think using ground-truth pitch, duration, and energy as the inputs of FastSpeech2 is somehow similar to using teacher forcing mode in Tacotron 2 (but still different). Looking forward to your result!

**Comment by thepowerfuldeez** [comment]
I am using evaluate() function as reference for generating mel-spectrograms for fine-tuning hifigan. So far so good

**Comment by leminhnguyen** [comment]
> @leminhnguyen It is a good suggestion. I think using ground-truth pitch, duration, and energy as the inputs of FastSpeech2 is somehow similar to using teacher forcing mode in Tacotron 2 (but still different). Looking forward to your result!

Last week, I'tried to finetuning the HifiGan with your suggestion. But I think the model suffered from the overfitting problem, The loss was very small but the quality of predicted audio was too bad.

**Comment by leminhnguyen** [comment]
> I am using evaluate() function as reference for generating mel-spectrograms for fine-tuning hifigan. So far so good

@thepowerfuldeez Great news, I think my proposed suggestion was suffered from overfitting. I will try your way in this week and report the results when it's done.

**Comment by leminhnguyen** [comment]
@thepowerfuldeez Did you need any preprocessing step for the audio before finetuning HifiGan with mel-spectrogram of FastSpeech.I've tried your suggestion but the predicted audio was pretty noisy.

**Comment by zhibin86** [comment]
@thepowerfuldeez, Hey I met the same issue as yours, The logs below, can you tell me how to fix it, thanks.

Load model codes:
    print('loading model from',model_path)
    

    model = FastSpeech2(py_vocab_size,hz_vocab_size)

    sd = torch.load(model_path,map_location='cpu')
    if 'model' in sd.keys(): #checkpoint file
        sd = sd['model'] # using only the model part(rather than the optim part)
    model.load_state_dict(sd)

    model.requires_grad = False
    model.eval()
    return model


Error logs:
jingjia@jingjia-System-Product-Name:~/TTS/mandarin-tts-master$ python synthesize.py --input="./input.txt"
Namespace(channel=2, duration=1.0, input='./input.txt', output_dir='./outputs/')
loading model from ./checkpoint/checkpoint_500000.pth
Traceback (most recent call last):
  File "synthesize.py", line 126, in <module>
    model = build_model().to(device)
  File "synthesize.py", line 50, in build_model
    model.load_state_dict(sd)
  File "/home/jingjia/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for FastSpeech2:
	Missing key(s) in state_dict: "decoder.speaker_fc.weight". 
	size mismatch for encoder.position_enc: copying a param with shape torch.Size([1, 1001, 256]) from checkpoint, the shape in current model is torch.Size([1, 2001, 256]).
	size mismatch for decoder.position_enc: copying a param with shape torch.Size([1, 1001, 256]) from checkpoint, the shape in current model is torch.Size([1, 2001, 256]).

**Comment by ming024** [comment]
@zhibin86 Did you change the ``max_seq_len`` parameter in ``model.json``.

**Comment by ming024** [comment]
closed #32

**Comment by lee9871** [comment]
I encountered the same problem, how did you solve it
@zhibin86

**Comment by lee9871** [comment]
size mismatch for speaker_emb.weight: copying a param with shape torch.Size([1, 256]) from checkpoint, the shape in current model is torch.Size([36, 256]).

**Comment by lee9871** [comment]
@leminhnguyen

**Comment by leminhnguyen** [comment]
Hey @lee9871 by reading the error logs, I guest the checkpoint was trained with the number of symbols equal to 1, but you tried to load the checkpoint to the model has the number of symbols equal to 36. So, the torch cannot copy the params from 2 mismatched models.
