### ISSUE TITLE
Unable to train with custom dataset

### ISSUE THREAD

**Issue by thepowerfuldeez** [ming024/FastSpeech2#33]
Hello! Thank you for your great work with this impl. I am trying to train a model on a custom dataset (different language). 
I didn't use MFA, I prepared data in LJSpeech format and edited `dataset.py` and preprocessing scripts. I didn't change symbols.py, however I use transliteration_cleaners before.

```
Original Traceback (most recent call last):
  File "/home/george/anaconda3/envs/reface_tts/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/george/anaconda3/envs/reface_tts/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/george/work/FastSpeech2/model/fastspeech2.py", line 81, in forward
    ) = self.variance_adaptor(
  File "/home/george/anaconda3/envs/reface_tts/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/george/work/FastSpeech2/model/modules.py", line 121, in forward
    x = x + pitch_embedding
RuntimeError: The size of tensor a (79) must match the size of tensor b (620) at non-singleton dimension 1
```

seems that something wrong with the pitch embedding and duration. As I didn't use mfa I set duration to some hardcoded value and didnt trim pitch array at preprocessing stage. How to properly setup data for training?

Thank you

**Comment by ming024** [comment]
@thepowerfuldeez  Maybe you have to make sure that the sum of the durations equals the length of the mel-spectrogram

**Comment by thepowerfuldeez** [comment]
@ming024 you are right, but where can i get these durations from?

**Comment by ming024** [comment]
@thepowerfuldeez Using MFA is one possible solution, or you can try to use the alignment of another TTS model (e.g. Tacotron 2) trained on your desired dataset, just like proposed in [FastSpeech](https://arxiv.org/abs/1905.09263). You can refer to [this implementation](https://github.com/xcmyz/FastSpeech/tree/7523d471e6d744636baf8acea4a39b004b6276f8)

**Comment by thepowerfuldeez** [comment]
@ming024 okay, i might try to use tacotron2 for alignment. Thank you! just thought maybe for ground truth durations there is a better way.

**Comment by jobanpreet495** [comment]
> Hello! Thank you for your great work with this impl. I am trying to train a model on a custom dataset (different language). I didn't use MFA, I prepared data in LJSpeech format and edited `dataset.py` and preprocessing scripts. I didn't change symbols.py, however I use transliteration_cleaners before.
> 
> ```
> Original Traceback (most recent call last):
>   File "/home/george/anaconda3/envs/reface_tts/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
>     output = module(*input, **kwargs)
>   File "/home/george/anaconda3/envs/reface_tts/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/george/work/FastSpeech2/model/fastspeech2.py", line 81, in forward
>     ) = self.variance_adaptor(
>   File "/home/george/anaconda3/envs/reface_tts/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/george/work/FastSpeech2/model/modules.py", line 121, in forward
>     x = x + pitch_embedding
> RuntimeError: The size of tensor a (79) must match the size of tensor b (620) at non-singleton dimension 1
> ```
> 
> seems that something wrong with the pitch embedding and duration. As I didn't use mfa I set duration to some hardcoded value and didnt trim pitch array at preprocessing stage. How to properly setup data for training?
> 
> Thank you



Add phonemes/IPA in cum_dict.py file.

**Comment by aabdumalikov** [comment]
I have checked the sum of mel and durations, all of are same, total also same.

Found 22832 matching duration and mel files
Validating files: 100%|█████████████████████████████████████████████████████████████████| 22832/22832 [00:11<00:00, 1942.88it/s]

Validation Results:
Total files checked: 22832
Files with mismatches: 0

No mismatches found! All durations match mel-spectrogram lengths.

But the issue is actual 

x = x + pitch_embedding
RuntimeError: The size of tensor a (60) must match the size of tensor b (154) at non-singleton dimension 1
