### ISSUE TITLE
Error in data preprocessing

### ISSUE THREAD

**Issue by Jacen789** [ming024/FastSpeech2#34]
这行代码`wav = wav / max(abs(wav)) * max_wav_value`
将会使音频产生噪声，像下面这种：
![image](https://user-images.githubusercontent.com/22630600/111283704-5e3b2a80-867a-11eb-9df4-effc48dde800.png)

**Comment by ming024** [comment]
Maybe changing it to ``wav = wav / max(abs(wav)) * max_wav_value * 0.95`` works?

**Comment by Jacen789** [comment]
Yes, It works that multiply it by 0.95.

**Comment by donghaiyw** [comment]
int_16 overflow : wav.astype(np.int16)
changing max_wav_value to 32767.0 will be work
max_wav_value: 32767.0

**Comment by ming024** [comment]
closed #34
