### ISSUE TITLE
No unaligned.txt when training the aligment by using MFA tool

### ISSUE THREAD

**Issue by hyysam** [ming024/FastSpeech2#39]
when I use MFA tool to train the AISHELL3, I can not have unaligned.txt file in the result folder. Should I open some args when training?

**Comment by ming024** [comment]
@hyysam maybe you should post an issue to the MFA project? In my opinion it means your alignment model is perfect so every utterance is aligned.

**Comment by EuphoriaCelestial** [comment]
> when I use MFA tool to train the AISHELL3, I can not have unaligned.txt file in the result folder. Should I open some args when training?

unaligned.txt file only contain a list of audio files that MFA cannot align. If you dont have that file in MFA output folder, that mean your data is all good, carry on to the next step

**Comment by ming024** [comment]
closed #39
