### ISSUE TITLE
train.py stop at 3321step

### ISSUE THREAD

**Issue by fangg2021** [ming024/FastSpeech2#40]
how can i train start from 3000 step?what command is?thanks

**Comment by fangg2021** [comment]
![QQ截图20210325202308](https://user-images.githubusercontent.com/80429579/112472439-08930c00-8d65-11eb-954f-6a2170c1bb29.png)

it stop at 1969 step this time……

**Comment by ming024** [comment]
@fangg2021 I cannot make any sense from this screenshot. Check your system log perhaps?

**Comment by fangg2021** [comment]
it does't have any errors, just Automatically stopped, sometimes ran fine. I just want to know, has any way to start from 3000 steps?
Now,i haved modify the train.xml's file params save_step=1000. But a little troublesome by this way...

**Comment by ming024** [comment]
@fangg2021 I have not faced this condition before...

**Comment by ming024** [comment]
closed #40

**Comment by leslie2046** [comment]
try  add "--restore_step 1969 "?
