### ISSUE TITLE
pinyin phoneme modeling on aishell3 dataset

### ISSUE THREAD

**Issue by joan126** [ming024/FastSpeech2#42]
I have some questions about pinyin phoneme modeling on aishell3 dataset:

1 when use MFA force-alignment tools to get alignments data, the am in MFA is trained on aishell3 dataset or pre_trained am model?

2 when use MFA to get alignment, the G2p model is retrained on aishell3 dataset scripts? the lexicon is limited to aishell3 dataset?

3 if there are prosody tags #1 #2 .. in texts , how to do alignment with MFA?

thanks in advance!!

**Comment by ming024** [comment]
@joan126 Hello, Here are my answers to the questions:

1. I failed to use the pretrained acoustic model provided by MFA so in my case the acoustic model is trained by myself on the AISHELL-3 dataset with my own lexicon, the one provided in ``lexicon``.
2. I did not use a G2P model for Mandarin TTS. The AISHELL-3 dataset provides the pinyin transcriptions so all I have to do is to map the pinyin transcription to a sequence of vowels and consonants, which is what the lexicon used for.
3. You can make the vowels tone-specific. For example, the vowel 'o' may be further divided into several different tone-specific ones such as 'o1', 'o2', 'o3'... In fact, this is what I do in the preprocessing stage.

**Comment by joan126** [comment]
> @joan126 Hello, Here are my answers to the questions:
> 
> 3. You can make the vowels tone-specific. For example, the vowel 'o' may be further divided into several different tone-specific ones such as 'o1', 'o2', 'o3'... In fact, this is what I do in the preprocessing stage.

thanks 
is this reply for my " if there are prosody tags #1 #2 .. in texts , how to do alignment with MFA?" ?

**Comment by ming024** [comment]
@joan126 Oh I misunderstood your problem before. What I mentioned is for the control of the tone in the Chinese language. If your prosody tags are related to the sentiment of the speech, or the lengths of breaks within an utterance, it may not be compatible with MFA as I realized. If these tags are extremely important, you could try other methods of alignment, for example, pertaining a Tacotron as in [FastSpeech](https://arxiv.org/abs/1905.09263).

**Comment by tobechao** [comment]
> @joan126 Hello, Here are my answers to the questions:
> 
> 1. I failed to use the pretrained acoustic model provided by MFA so in my case the acoustic model is trained by myself on the AISHELL-3 dataset with my own lexicon, the one provided in `lexicon`.
> 2. I did not use a G2P model for Mandarin TTS. The AISHELL-3 dataset provides the pinyin transcriptions so all I have to do is to map the pinyin transcription to a sequence of vowels and consonants, which is what the lexicon used for.
> 3. You can make the vowels tone-specific. For example, the vowel 'o' may be further divided into several different tone-specific ones such as 'o1', 'o2', 'o3'... In fact, this is what I do in the preprocessing stage.

@ming024 Hello, ming024，sorry to bother you，I use mfa 2.0.0rc2 version and AISHELL3 datasets and commond "mfa train raw_data/AISHELL3 lexicon/pinyin-lexicon-r.txt result_aligned_v2 -v --clean --overwrite -j 4" to train mfa, The output TextGrid is not same with yours, I have not aligned in my results, Which version are you using please？how to train mfa ?
examples:SSB00050056.wav:
The picture below is yours:
![image](https://user-images.githubusercontent.com/24928749/150305898-2d5b55f8-bdf1-4c2f-a2b4-5c1760468524.png)

The picture below is mine:
![image](https://user-images.githubusercontent.com/24928749/150306026-68674fcc-ecfd-45fb-af67-07dd3eb41a0e.png)

What do you recommend? thanks

**Comment by leslie2046** [comment]
> I have some questions about pinyin phoneme modeling on aishell3 dataset:
> 
> 1 when use MFA force-alignment tools to get alignments data, the am in MFA is trained on aishell3 dataset or pre_trained am model?
> 
> 2 when use MFA to get alignment, the G2p model is retrained on aishell3 dataset scripts? the lexicon is limited to aishell3 dataset?
> 
> 3 if there are prosody tags #1 #2 .. in texts , how to do alignment with MFA?
> 
> thanks in advance!!

in my case,add a cleaner in text/cleaners.py  and enable it in config/xxx/preprocessor.yaml.and you will clean them out
def remove_prosodylabelings(text):
    text=re.sub('#1','',text)
    text=re.sub('#2','',text)
    text=re.sub('#3','',text)
    text=re.sub('#4','',text)
    return collapse_punctuation(text)
