### ISSUE TITLE
raw data path 

### ISSUE THREAD

**Issue by zaidalyafeai** [ming024/FastSpeech2#45]
The `preprocess.yaml` file for LJSpeech contains the attribute `raw_path: "./raw_data/LJSpeech"`, How to obtain raw data from LJSpeech-1.1 ?

**Comment by zaidalyafeai** [comment]
I forgot to run `python3 prepare_align.py`.

**Comment by gaoyiyao** [comment]
raw_data中是数据集吗，

corpus_path: "/home/ming/Data/LJSpeech-1.1"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/LJSpeech"
  preprocessed_path: "./preprocessed_data/LJSpeech_paper"这四个路径分别指向什么
