### ISSUE TITLE
MFA alignment is not accurate

### ISSUE THREAD

**Issue by joan126** [ming024/FastSpeech2#49]
Hi, I am using MFA to do force alignment on my own dataset. I found that the alignment results is not accurate.  

my dataset is 15 hours, maybe not big enough for training am from scratch. after increased my dataset to 30 hours, still not accurate. Do you have some trick to improve the alignment?

**Comment by WuMing757** [comment]
what's the problem with your synthesized result? Maybe you can manually fix it without training MFA.

**Comment by ming024** [comment]
@joan126 I think 30 hours of training data is enough. Maybe try to check the data quality and the transcript and laxicon.

**Comment by joan126** [comment]
> @joan126 I think 30 hours of training data is enough. Maybe try to check the data quality and the transcript and laxicon.

data are all high quality tts data. the aligned result has a time offset about 30ms

**Comment by ming024** [comment]
@joan126 hmm I am not sure about the condition you faced, maybe you can consult the MFA owner.

**Comment by joan126** [comment]
> @joan126 hmm I am not sure about the condition you faced, maybe you can consult the MFA owner.

thxs

**Comment by ming024** [comment]
closed #49
