### ISSUE TITLE
Problem occurred when increasing batch size

### ISSUE THREAD

**Issue by sdc17** [ming024/FastSpeech2#5]
Hi, thanks for your great work!
I was training this repo on my own dataset.
Everything was OK when I set batch size as `64`. I got training log and checkpoints of model.
But when I tried to increase batch size above `64` (There were enough free memory on my GPU), the `training.py` crashed before it printed any a single line of running log or error message.

Usage of GPU when batch size was `64`:
![image](https://user-images.githubusercontent.com/47023705/87944560-23c0c400-cad2-11ea-8745-fda4d277f240.png)
Any idea on how did this happen?
Thanks!

**Comment by ming024** [comment]
In ``train.py``
https://github.com/ming024/FastSpeech2/blob/172d2ea9a03b8dc6751388bacc26c15c801cbb4d/train.py#L28-L29

the dataloader defaults to sample ``batchsize ** 2`` instances of samples at each iteration. And in ``dataset.py``
https://github.com/ming024/FastSpeech2/blob/172d2ea9a03b8dc6751388bacc26c15c801cbb4d/dataset.py#L95-L112

the samples are sorted according to the lengths to maximize GPU utility.

However, the LJSpeech dataset has only 13100 samples, and 128**2 = 16384 is too large. If you want to set a large batch size you have to modify the ``collate_fn`` in ``dataset.py`` by yourself.

**Comment by sdc17** [comment]
Thanks for your kind reply! I'll try that.

**Comment by leijue222** [comment]
> I was training this repo on my own dataset.
Have you tried training it on a Chinese dataset?

**Comment by sdc17** [comment]
> > I was training this repo on my own dataset.
> 
> @sdc17 Have you tried training it on a Chinese dataset?
No, I haven't.
