### ISSUE TITLE
TextGrid.zip

### ISSUE THREAD

**Issue by neerajkuhike** [ming024/FastSpeech2#6]
How could I make the textgrid file if I have to try it for other datasets.

**Comment by ming024** [comment]
The textgrid files used in this repo are obtained by the [Montreal Forced Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/). The MFA is actually a pretrained acoustic model and has supports for several languages.

**Comment by neerajkuhike** [comment]
Hi I have tried it with MFA 1.1.0 beta2 version and not creating the textgrid file . The latest version MFA version 1.0.1 is able to create the Textgrid file with text and wav file  and has other parameters like bleu .
