### ISSUE TITLE
Coding error when run preprocessor.py

### ISSUE THREAD

**Issue by EuphoriaCelestial** [ming024/FastSpeech2#64]
Hello, I am trying to train a model using LJSpeech dataset, following steps in README.md and got this error:

`$ python3 preprocess.py config/LJSpeech/preprocess.yaml
Processing Data ...
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "preprocess.py", line 15, in <module>
    preprocessor.build_from_path()
  File "/FastSpeech2/preprocessor/preprocessor.py", line 85, in build_from_path
    if len(pitch) > 0:
UnboundLocalError: local variable 'pitch' referenced before assignment
`
I've already downloaded TextGrid files and put them in '/FastSpeech2/preprocessed_data/LJSpeech/LJSpeech/TextGrid'

**Comment by yileld** [comment]
its because the code didnt skip when some textgrid files are missing，just add “else：continue” in line 84

**Comment by EuphoriaCelestial** [comment]
is this correct? line 77 to 89

`                if os.path.exists(tg_path):
                    ret = self.process_utterance(speaker, basename)
                    if ret is None:
                        continue
                    else:
                        info, pitch, energy, n = ret
                    out.append(info)
                else:
                    continue
                if len(pitch) > 0:
                    pitch_scaler.partial_fit(pitch.reshape((-1, 1)))
                if len(energy) > 0:
                    energy_scaler.partial_fit(energy.reshape((-1, 1)))`

It seem to fixed the bug above, but now I have another

`$ python3 preprocess.py config/LJSpeech/preprocess.yaml
Processing Data ...
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.52it/s]
Computing statistic quantities ...
Traceback (most recent call last):
  File "preprocess.py", line 15, in <module>
    preprocessor.build_from_path()
  File "/media/hangtg/Data/fastspeech2/FastSpeech2/preprocessor/preprocessor.py", line 96, in build_from_path
    pitch_mean = pitch_scaler.mean_[0]
AttributeError: 'StandardScaler' object has no attribute 'mean_'
`

**Comment by leminhnguyen** [comment]
@EuphoriaCelestial I think you need to format the code with markdown syntax and preview before posting. So I or someone can read the code and help you:

**Comment by EuphoriaCelestial** [comment]
> 
> 
> @EuphoriaCelestial I think you need to format the code with markdown syntax and preview before posting. So I or someone can read the code and help you:

it is in this file https://github.com/ming024/FastSpeech2/blob/master/preprocessor/preprocessor.py , line 85

then I added else continue as @yileld suggest

```
                if os.path.exists(tg_path):
                    ret = self.process_utterance(speaker, basename)
                    if ret is None:
                        continue
                    else:
                        info, pitch, energy, n = ret
                    out.append(info)
		else:
		    continue
                if len(pitch) > 0:
                    pitch_scaler.partial_fit(pitch.reshape((-1, 1)))
                if len(energy) > 0:
                    energy_scaler.partial_fit(energy.reshape((-1, 1)))
```

**Comment by EuphoriaCelestial** [comment]
> 
> 
> > @EuphoriaCelestial I think you need to format the code with markdown syntax and preview before posting. So I or someone can read the code and help you:
> 
> it is in this file https://github.com/ming024/FastSpeech2/blob/master/preprocessor/preprocessor.py , line 85
> 
> then I added else continue as @yileld suggest
> 
> ```
>                 if os.path.exists(tg_path):
>                     ret = self.process_utterance(speaker, basename)
>                     if ret is None:
>                         continue
>                     else:
>                         info, pitch, energy, n = ret
>                     out.append(info)
> 		else:
> 		    continue
>                 if len(pitch) > 0:
>                     pitch_scaler.partial_fit(pitch.reshape((-1, 1)))
>                 if len(energy) > 0:
>                     energy_scaler.partial_fit(energy.reshape((-1, 1)))
> ```

it fixed the UnboundLocalError but create another AttributeError like above

**Comment by leminhnguyen** [comment]
I think your textgrid path was wrong so the following lines have never been executed:
```python
 if len(pitch) > 0:
     pitch_scaler.partial_fit(pitch.reshape((-1, 1)))
 if len(energy) > 0:
     energy_scaler.partial_fit(energy.reshape((-1, 1)))
```
So the `AttributeError: 'StandardScaler' object has no attribute 'mean_'` was thrown for the empty `pitch_scaler`

**Comment by EuphoriaCelestial** [comment]
turn out I placed TextGrid files in the wrong folder structure, after put them in correct path the code worked fine
thanks you guys for your help, and please update the guide line, maybe add a folder structure image will help

**Comment by lee9871** [comment]
hi，I have the same problem. How did you solve it

**Comment by lee9871** [comment]
@EuphoriaCelestial

**Comment by EuphoriaCelestial** [comment]
> hi，I have the same problem. How did you solve it

I just move the TextGrid files to the correct path
you can check where the preproccessor.py are expecting TextGrid files by adding this line of code at line 77:
`print(tg_path)`

**Comment by lee9871** [comment]
Thank you for being so timely
@EuphoriaCelestial

**Comment by leslie2046** [comment]
yes,you are right @EuphoriaCelestial

**Comment by Lakhjeet1082** [comment]
> > hi，I have the same problem. How did you solve it
> 
> I just move the TextGrid files to the correct path you can check where the preproccessor.py are expecting TextGrid files by adding this code at line 77: `print(tg_path)`

Thank you this helped in solving my issue

**Comment by aabdumalikov** [comment]
pitch_mean = pitch_scaler.mean_[0]
AttributeError: 'StandardScaler' object has no attribute 'mean_'
