### ISSUE TITLE
电音机械音噪声如何从根源上去除呢？

### ISSUE THREAD

**Issue by oniondai** [ming024/FastSpeech2#76]

**Comment by MrYANG23** [comment]
> _No description provided._

hi I have the same issue , did you solved it?

**Comment by oniondai** [comment]
> > _No description provided._
> 
> hi I have the same issue , did you solved it?

Sorry, this problem has not been solved for the time being. Strictly speaking, this belongs to echo noise. For relevant processing methods, please refer to Microsoft's echo cancellation competition https://github.com/microsoft/AEC-Challenge
