### ISSUE TITLE
trained on dataset with another sampling rate

### ISSUE THREAD

**Issue by yileld** [ming024/FastSpeech2#78]
I tried to train the model with biaobei Chinese dataset, which is 48kHz. And I change the code in preprocess.yaml, preprocessor.py and tools.py to fit the different sampling rate. But the result is bad, sounds like the pitch or energy is very high. Is there something wrong? Should I change the parameters in pyworld.dio() in preprocessor.py or what?

https://user-images.githubusercontent.com/13084050/123570638-39b72880-d7fb-11eb-8eb0-61d45ad6bd69.mov

and if I change the output sampling rate with 22050, the voice seems correct with low speed.

https://user-images.githubusercontent.com/13084050/123606583-9e8c7600-d82f-11eb-8010-03789a910d67.mov

**Comment by leslie2046** [comment]
how did you solved this?
