### ISSUE TITLE
Energy and F0 for other dataset 

### ISSUE THREAD

**Issue by neerajkuhike** [ming024/FastSpeech2#8]
Ho do I find the below parameters for other datasets 

# Quantization for F0 and energy
### for LJSpeech ###
f0_min = 71.0
f0_max = 795.8
energy_min = 0.0
energy_max = 315.0
### for Blizzard2013 ###
#f0_min = 71.0
#f0_max = 786.7
#energy_min = 21.23
#energy_max = 101.02

**Comment by ming024** [comment]
@neerajkuhike You can get these statistics from the output message of ``python3 preprocess.py`` .
