### ISSUE TITLE
Invalid voice generated

### ISSUE THREAD

**Issue by Moonmore** [ming024/FastSpeech2#83]
When I use the method in the readme for training, I get the corresponding speech synthesis model. When performing speech synthesis inference, it is found that the generated speech is empty speech.

my sysnthsize: python synthesize.py --text "大家好" --speaker_id 1 --restore_step 600000 --mode single -p config/AISHELL3/preprocess.yaml -m configure/AISHELL3/model.yaml -t config/AISHELL3/train.yaml

**Comment by Moonmore** [comment]
> When I use the method in the readme for training, I get the corresponding speech synthesis model. When performing speech synthesis inference, it is found that the generated speech is empty speech.
> 
> my sysnthsize: python synthesize.py --text "大家好" --speaker_id 1 --restore_step 600000 --mode single -p config/AISHELL3/preprocess.yaml -m configure/AISHELL3/model.yaml -t config/AISHELL3/train.yaml

**Comment by zaynabmu** [comment]
how did you solve it? I faced the same issue 

thank you in advance

**Comment by msinanyildirim** [comment]
Going through the same thing at the moment. Do you have any suggestions?
