### ISSUE TITLE
UnboundLocalError: local variable 'pitch' referenced before assignment

### ISSUE THREAD

**Issue by wanwen1405** [ming024/FastSpeech2#92]
Hi!

After typing "python preprocess.py config/LibriTTS/preprocess.yaml" into the terminal, the output i received is this

line 85, in build_from_path  
    if len(pitch) > 0:
UnboundLocalError: local variable 'pitch' referenced before assignment

how do i debug this?

**Comment by wanwen1405** [comment]
sorry, it was just an indentation issue.

**Comment by ninmiao** [comment]
> sorry, it was just an indentation issue.



> sorry, it was just an indentation issue.

Hi,

I am faced with same problem. Can you explain your solutions?

Thanks

**Comment by alienfist** [comment]
@wanwen1405 I encountered the same problem. How did you solve it?
